### ISSUE TITLE
M5 Implementation

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#25]
## Subtasks
- [ ] Add new user (firebase) - Teju
- [ ] Pull login from database - Rishi
- [ ] Designate account type (spinner) - Sungjae
- [ ] Password matching in registration - Sungjae
- [ ] Edit user profile (new ui screen) - Chaes (firebase) and Kavin  (activity / ui) 
- [ ] OTHER (Javadocs, no hardcoded user) -EVERYONE COMMENT AS YOU GO

## Description from T-Square
Add the registration screen to your app. A new user should be able to register by entering their information (like name, id, and password). If accepted, the new user should be added to the system. If cancelled, the user should not be added.
During registration, the new user may designate their account type (User, Worker, Manager or Admin). In a real application, we would have controls for these, but for this class project, we will let the individual enter their capabilities during registration.
When registration is working, you may remove the hard-coded user/pass from the app.
You should also have the ability for a user to create and edit their profile. Their profile consists of all their information that the application must maintain like email address, home address, title, etc.
NOTE THAT PERSISTENCE IS NOT REQUIRED AT THIS POINT. IT IS OK TO HAVE TO RE-ENTER USERS FROM SCRATCH EACH TIME THE APPLICATION IS STARTED.

Implementation (45)
User registration screen is integrated into app .............................. 05
Accepted registration adds new user to system ................. 05
Cancelled registration does not add new user ................. 05
Back-end records list of registered users (UI communicates with model) ................... 10
User type (user, worker, manager, admin) created ..... 10
User profile edited ...... 05
Javadoc / comments .......................................... 05
