### ISSUE TITLE
M5 User Login via Firebase

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#27]
## Subtasks
- [ ] Finalize firebase integration
- [ ] Allow users to register for accounts (account creation via firebase)
- [ ] Javadoc and comment everything!!!
- [ ] Anything else you think of

## Description from T-Square
Add the registration screen to your app. A new user should be able to register by entering their information (like name, id, and password). If accepted, the new user should be added to the system. If cancelled, the user should not be added

User registration screen is integrated into app .............................. 05
Accepted registration adds new user to system ................. 05
Cancelled registration does not add new user ................. 05
Back-end records list of registered users (UI communicates with model) ................... 10
