### ISSUE TITLE
M5 Firebase Login

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#28]
## Subtasks
- [ ] Connect user login and authentication to firebase
- [ ] Javadoc and comment everything!!!
- [ ] Anything else you think of

## Description from T-Square
No description... just work with Teju and firebase to make sure that a user is able to login to the application given they provide valid credentials.
