### ISSUE TITLE
M5 User Profile

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#29]
## Subtasks
- [ ] Create new activity to allow user to input appropriate data
- [ ] Integrate the profile information with firebase to ensure everything is store
- [ ] Javadoc and comment everything!!

## Description from T-Square
You should also have the ability for a user to create and edit their profile. Their profile consists of all their information that the application must maintain like email address, home address, title, etc.

User profile edited ...... 05
Javadoc / comments .......................................... 05
