### ISSUE TITLE
M2 Working with Git P2

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#3]
## Subtasks
- [x] Complete the code withing Person2.java and commit changes
- [x] Edit the file edu.gatech.cs2340.antlab.pkg1.AntLabMain.java for Person2
- [x] Add readme.p2.txt to the repository... include name and email (don't forget to commit)
- [x] Delete useless.p2.txt from the repository

*MAKE SURE YOU HAVE A GOOD DESCRIPTION FOR ALL OF YOUR COMMITS

## Description from T-Square
You should work with your Git repository for a bit and in doing so you should complete all of the following tasks at least once:

Edit and commit files as detailed below.
If you examine the src directory, you will see the files Person1.java Person2.java Person3.java Person4.java Person5.java (located in the edu.gatech.cs2340.antlab.person package)

Each person on the team should choose ONE of these so that everyone is working on a different file.

Now examine your individual file and complete the required method. The javadoc comment will explain what has to be done.

Commit your changes and push back to Git. Now each team member should edit the file edu.gatech.cs2340.antlab.pkg1.AntLabMain.java at the line indicated. You are basically sending your name to the constructor of the class you edited previously. Since you are all editing the same file, you will need to handle any merge requirements yourselves. You might want to get together and commit files to force a merge so you get some practice doing merges. You will run into them during the project.

Add and remove files
Each team member should add a text file to the top level directory labeled readme.pn.txt where the pn would be p1, p2, p3, p4 or p5 based upon which person you are for the lab. The contents of the file can really be anything, but should include your name and email. Each team member should delete the text file useless.pn.txt where pn is p1,p2, p3, p4 or p5 based on your team member number. Do NOT delete the wrong files!!

Use good descriptive Log comments for your changes/commits

Roll back changes by viewing your original branch from an earlier step. Verify that none of the changes you have made are in the project version you checked out.

View Git logs. You can do this on github by viewing the blame and graphs provided
View a diff between two versions of a file
Keep playing with git until you feel comfortable. You will probably be using it extensively for the remainder of the semester.
