### ISSUE TITLE
M5 User Type and Password Verification

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#30]
## Subtasks
- [ ] Add a spinner to the registration to allow the user to choose what type of user they are. You can base this off the spinner implementation that we had to do for M3. You'll likely need to create an enum for the four different user types (User, Worker, Manager, Administrator)
- [ ] Add a method in the registration java class that checks the two passwords fields and returns true if their contents are equal.
- [ ] Javadoc and comment everything!!!

## Description from T-Square
During registration, the new user may designate their account type (User, Worker, Manager or Admin). In a real application, we would have controls for these, but for this class project, we will let the individual enter their capabilities during registration.

User type (user, worker, manager, admin) created ..... 10
