### ISSUE TITLE
M6 Create Report Activity

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#34]
## Subtasks
- [ ] Create a new activity for making water reports
- [ ] Create UI and hook up buttons
- [ ] Load information from the user passed via intent
- [ ] Create a new instance of the WaterReport class with provided data

## Description from T-Square
The submit report should prompt for all required information.
Canceling the report does not save any information.

Report should include:
Date and time of report (can be autogenerated by application)
Report Number (must be autogenerated by application)
Name of reporter (can be autogenerated from user information)
Location of water (manually entered. using any kind of location services or gps is extra credit).
Type of water (Bottled, Well, Stream, Lake, Spring, Other) (Use a spinner to select from an enum)
Condition of water (Waste, Treatable-Clear, Treatable-Muddy, Potable) (another spinner)

Report screen enters all required information .................... 10
Javadoc, Comments........................................10
