### ISSUE TITLE
M6 WaterReport Class and Enums

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#35]
## Subtasks
- [ ] Create a WaterReport class that holds all necessary data (see below for requirements)
- [ ] Create an enum for type of water (see below for values)
- [ ] Create an enum for water Condition (see below for values)

## Description from T-Square
Date and time of report 
Report Number
Name of reporter
Location of water.
Type of water (Bottled, Well, Stream, Lake, Spring, Other) <= ENUM
Condition of water (Waste, Treatable-Clear, Treatable-Muddy, Potable) <= ENUM 

Javadoc, Comments ........................................10
