### ISSUE TITLE
M6 Firebase Implementation

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#36]
## Subtasks
- [ ] Create a place in firebase to store all created water reports
- [ ] Edit the create report activity to save the newly created report to firebase
- [ ] In the show water report activity, get all water reports from firebase so they can be listed

## Description from T-Square
Submitting the report should store it in the database

After submission report is stored in model ....................... 10 (database)
Javadoc, Comments ........................................10
