### ISSUE TITLE
M7 Map Implementation

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#41]
## Subtasks
- [ ] Create an activity to display the map (all necessary API stuff)
- [ ] Display all reports on the map by pulling information from list of reports (someone else will get this from firebase)
- [ ] Clicking the pins on the map should provide info about the report
- [ ] Javadocs!!!!!!!!!

## Description from T-Square
You should now implement the water availability screen. This screen should display a Map (you can use any api you wish, although google maps is pretty well documented.). The map should have markers at each location that water has been reported. Clicking on the pin should provide information from the water report.

Show that previous functionality still works.
Provide a way to navigate to the water availability screen.
Display a map
Place pins at the locations of each report
Show report details for a pin when it is selected by the user

Previous functionality still works ................................. 05
Navigation option to show water availability screen .............. 05
Map displays ................. 15
Pins are on map at each report location .............. 10
Selecting a pin shows details of the report .......... 10
Javadocs and code style, Design Discussion ............... 15
