### ISSUE TITLE
M8 Main XMLs

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#47]
## Subtasks
- [x] Create three new XML files for the main activity
- [x] XML for Worker
- [x] XML for Manager
- [x] XML for Administrator

## Description
Our main page needs to have different buttons for each type of user. For this to work, you should create three new XML files based on the current XML for the main activity (basically copy and paste... make sure all the ids are the same).
- In the worker xml, you should create a button to create a water purity report.
- In the manager xml, you should have both the additional button that worker added (same id), and a button for viewing water reports. 
- For now, the administrator xml can be a copy of the manager xml.
