### ISSUE TITLE
M9 Histogram Prompt

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#53]
## Subtasks
- [ ] Prompt user for correct info
- [ ] Ensure user enters valid info
- [ ] Allow user to select a specific water report, and use the purity reports linked to that water report
(basically just adapt your recycler view so that the user can select a water report from that)
- [ ] Work with Teju to update the creation of purity reports to allow the user to select a parent water report
(same functionality as the previous bullet)
- [ ] Pass info to graphing activity

## Description from T-Square
We will also display the water quality history graph. The system will prompt a manager for the setup information (like year and location).

System prompts the manager for setup information for the report

Managers can request a history graph (user and worker cannot) … 05
Manager can enter setup information for graph .... 10

Design review and javadocs … 10
