### ISSUE TITLE
General Repair

### ISSUE THREAD

**Issue by chase-lewis** [chase-lewis/STARLabs39#55]
## Subtasks
- [ ] Fix the hacky implementation from last week
- [ ] Create some UI that doesn't look like it was created by a caveman with dementia
- [ ] Hookup the stuff for this week with the new UI

## Description from T-Square
GAH idk
